character_data: dict[str, str | int] = {
    "data": {
        "name": "string",
        "skin": "men1",
        "level": 0,
        "xp": 0,
        "max_xp": 0,
        "total_xp": 0,
        "gold": 0,
        "speed": 0,
        "mining_level": 0,
        "mining_xp": 0,
        "mining_max_xp": 0,
        "woodcutting_level": 0,
        "woodcutting_xp": 0,
        "woodcutting_max_xp": 0,
        "fishing_level": 0,
        "fishing_xp": 0,
        "fishing_max_xp": 0,
        "weaponcrafting_level": 0,
        "weaponcrafting_xp": 0,
        "weaponcrafting_max_xp": 0,
        "gearcrafting_level": 0,
        "gearcrafting_xp": 0,
        "gearcrafting_max_xp": 0,
        "jewelrycrafting_level": 0,
        "jewelrycrafting_xp": 0,
        "jewelrycrafting_max_xp": 0,
        "cooking_level": 0,
        "cooking_xp": 0,
        "cooking_max_xp": 0,
        "hp": 0,
        "haste": 0,
        "critical_strike": 0,
        "stamina": 0,
        "attack_fire": 0,
        "attack_earth": 0,
        "attack_water": 0,
        "attack_air": 0,
        "dmg_fire": 0,
        "dmg_earth": 0,
        "dmg_water": 0,
        "dmg_air": 0,
        "res_fire": 0,
        "res_earth": 0,
        "res_water": 0,
        "res_air": 0,
        "x": 0,
        "y": 0,
        "cooldown": 0,
        "cooldown_expiration": "2019-08-24T14:15:22Z",
        "weapon_slot": "string",
        "shield_slot": "string",
        "helmet_slot": "string",
        "body_armor_slot": "string",
        "leg_armor_slot": "string",
        "boots_slot": "string",
        "ring1_slot": "string",
        "ring2_slot": "string",
        "amulet_slot": "string",
        "artifact1_slot": "string",
        "artifact2_slot": "string",
        "artifact3_slot": "string",
        "consumable1_slot": "string",
        "consumable1_slot_quantity": 0,
        "consumable2_slot": "string",
        "consumable2_slot_quantity": 0,
        "task": "string",
        "task_type": "string",
        "task_progress": 0,
        "task_total": 0,
        "inventory_max_items": 0,
        "inventory": [{"slot": 0, "code": "string", "quantity": 0}],
    }
}

movement_data = {
    "data": {
        "destination": {"x": 1, "y": 1},
        "item": {"name": "Sword"},
        "character": {
            "name": "string",
            "skin": "men1",
            "level": 0,
            "xp": 0,
            "max_xp": 0,
            "total_xp": 0,
            "gold": 0,
            "speed": 0,
            "mining_level": 0,
            "mining_xp": 0,
            "mining_max_xp": 0,
            "woodcutting_level": 0,
            "woodcutting_xp": 0,
            "woodcutting_max_xp": 0,
            "fishing_level": 0,
            "fishing_xp": 0,
            "fishing_max_xp": 0,
            "weaponcrafting_level": 0,
            "weaponcrafting_xp": 0,
            "weaponcrafting_max_xp": 0,
            "gearcrafting_level": 0,
            "gearcrafting_xp": 0,
            "gearcrafting_max_xp": 0,
            "jewelrycrafting_level": 0,
            "jewelrycrafting_xp": 0,
            "jewelrycrafting_max_xp": 0,
            "cooking_level": 0,
            "cooking_xp": 0,
            "cooking_max_xp": 0,
            "hp": 0,
            "haste": 0,
            "critical_strike": 0,
            "stamina": 0,
            "attack_fire": 0,
            "attack_earth": 0,
            "attack_water": 0,
            "attack_air": 0,
            "dmg_fire": 0,
            "dmg_earth": 0,
            "dmg_water": 0,
            "dmg_air": 0,
            "res_fire": 0,
            "res_earth": 0,
            "res_water": 0,
            "res_air": 0,
            "x": 0,
            "y": 0,
            "cooldown": 0,
            "cooldown_expiration": "2019-08-24T14:15:22Z",
            "weapon_slot": "string",
            "shield_slot": "string",
            "helmet_slot": "string",
            "body_armor_slot": "string",
            "leg_armor_slot": "string",
            "boots_slot": "string",
            "ring1_slot": "string",
            "ring2_slot": "string",
            "amulet_slot": "string",
            "artifact1_slot": "string",
            "artifact2_slot": "string",
            "artifact3_slot": "string",
            "consumable1_slot": "string",
            "consumable1_slot_quantity": 0,
            "consumable2_slot": "string",
            "consumable2_slot_quantity": 0,
            "task": "string",
            "task_type": "string",
            "task_progress": 0,
            "task_total": 0,
            "inventory_max_items": 0,
            "inventory": [{"slot": 0, "code": "string", "quantity": 0}],
        },
        "fight": {
            "xp": 0,
            "gold": 0,
            "drops": [{"code": "string", "quantity": 0}],
            "turns": 0,
            "monster_blocked_hits": {
                "fire": 0,
                "earth": 0,
                "water": 0,
                "air": 0,
                "total": 0,
            },
            "player_blocked_hits": {
                "fire": 0,
                "earth": 0,
                "water": 0,
                "air": 0,
                "total": 0,
            },
            "logs": ["string"],
            "result": "win",
        },
    }
}


monster_data = {
    "data": {
        "name": "DireWolf",
        "code": "monster",
        "level": 4,
        "hp": 0,
        "attack_fire": 0,
        "attack_earth": 0,
        "attack_water": 0,
        "attack_air": 0,
        "res_fire": 0,
        "res_earth": 0,
        "res_water": 0,
        "res_air": 0,
        "min_gold": 0,
        "max_gold": 0,
        "drops": [{"code": "string", "rate": 1, "min_quantity": 1, "max_quantity": 1}],
    }
}


resource_data = {
    "data": {
        "name": "ingot",
        "code": "ores",
        "skill": "mining",
        "level": 0,
        "drops": [{"code": "string", "rate": 1, "min_quantity": 1, "max_quantity": 1}],
    }
}

map_data = {
    "data": {
        "name": "candy_land",
        "skin": "string",
        "x": 0,
        "y": 0,
        "content": {"type": "string", "code": "string"},
    }
}

events_data = {
    "data": [
        {
            "name": "string",
            "map": {
                "name": "string",
                "skin": "string",
                "x": 0,
                "y": 0,
                "content": {"type": "string", "code": "string"},
            },
            "previous_skin": "string",
            "duration": 0,
            "expiration": "2019-08-24T14:15:22Z",
            "created_at": "2019-08-24T14:15:22Z",
        }
    ]
}
